# These are supported funding model platforms

github: [JSMonk]
patreon: rage_monk
ko_fi: # Replace with a single Ko-fi username
tidelift: npm/@hegel
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
